<?php


class WzywigController{
    private $wzywigservice;

    function __construct(){
        //$this->wzywigservice = new WzywigService();
    }

    public function index(){
          // Start output buffering
            ob_start();
    
            // Include the offerMail.php file and execute its PHP code
            require __DIR__ . '/../views/home/index.php';
    
            // Capture the output generated by the PHP code and store it in a variable
            $body = ob_get_clean();
        require __DIR__ . '/../views/wzywig/index.php';
    }
}
?>